# -*- coding: utf-8 -*-
"""이진검색.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hm9lFZUgz3cmvffp1LqBTXIvv-I38_l7
"""

## 함수
import random
def binSearch(ary, fData) :
    pos = -1
    start = 0
    end = len(ary)-1
    while (start <= end) :
        mid = (start + end) // 2
        if (ary[mid] == fData) :
            pos = mid
            break
        elif (ary[mid] < fData) :
            start = mid + 1
        else :
            end = mid - 1

    return pos

## 변수
SIZE=10
dataAry = [random.randint(40, 200) for _ in range(SIZE)]
dataAry.sort()
findData = random.choice(dataAry)

## 메인
print('배열-->', dataAry)
position = binSearch(dataAry, findData)
if (position == -1) :
    print(findData,'는', position, '없어요 ㅠㅠ')
else :
    print(findData,'는', position, '위치에 있음 ^^')