# -*- coding: utf-8 -*-
"""재귀.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/191GqRJPhFT8DeaudIY8JvSlyQbtEiYwX
"""

## 함수
def openBox():
  global count
  print("상자 열기!")
  count -= 1
  if (count == 0):
    print("*** 선물 넣기 ***")
    return
  openBox()
  print("상자 닫기##")


## 메인
count = 3
openBox()

