# -*- coding: utf-8 -*-
"""선택정렬.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rKaKaY_Xk6upYbSdN0h48dPZXDeeLeJx
"""

## 함수
def  findMinIndex(ary) :
    minIdx = 0
    for i in range(1, len(ary) ) :
        if (ary[minIdx] > ary[i]) :
            minIdx = i
    return minIdx

## 변수
testAry = [55, 88, 33, 77]

## 메인
minPos = findMinIndex(testAry)
print('최솟값-->', testAry[minPos])

## 함수
import random

## 변수
SIZE = 8
before = [random.randint(40,200) for _ in range(SIZE)]
after = []

## 메인
print("정렬 전 -->", before)
for i in range(SIZE):
  minPos = findMinIndex(before)
  after.append(before[minPos])
  del(before[minPos])
print("정렬 후 -->", after)